---
- name: Disable services
  ansible.builtin.command: "pro disable {{ item }}"
  become: true
  register: _reg_pro_disable
  when: item in _ubuntu_pro_services
  loop: "{{ ubuntu_pro_disabled_services }}"
  changed_when: _reg_pro_disable.rc == 0
  failed_when:
    - _reg_pro_disable.rc != 0
    - ('is not currently enabled' not in _reg_pro_disable.stdout_lines[0])
