---
- name: Include tasks 'unregister.yml'
  ansible.builtin.include_tasks: unregister.yml
  when: ubuntu_pro_state == 'absent' or ubuntu_pro_state == 'detached'

- name: Include tasks 'uninstall.yml'
  ansible.builtin.include_tasks: uninstall.yml
  when: ubuntu_pro_state == 'absent'

- name: Include tasks for present or attached ubuntu_pro_state
  block:
    - name: Include tasks 'validate_ubuntu_lts_version.yml'
      ansible.builtin.include_tasks: validate_ubuntu_lts_version.yml

    - name: Include tasks 'requirements.yml'
      ansible.builtin.include_tasks: requirements.yml

    - name: Include tasks 'configure.yml'
      ansible.builtin.include_tasks: configure.yml

    - name: Include tasks 'register.yml'
      ansible.builtin.include_tasks: register.yml

    - name: Include tasks 'enable_services.yml'
      ansible.builtin.include_tasks: enable_services.yml
      when: ubuntu_pro_enabled_services is defined

    - name: Include tasks 'disable_services.yml'
      ansible.builtin.include_tasks: disable_services.yml
      when: ubuntu_pro_disabled_services is defined
  when: ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached'
