---
- name: Include tasks 'validate_ubuntu_lts_version.yml'
  include_tasks: validate_ubuntu_lts_version.yml

# - name: Include tasks 'requirements.yml'
#   include_tasks: requirements.yml

- name: Include tasks 'configure.yml'
  include_tasks: configure.yml

- name: Include tasks 'register.yml'
  include_tasks: register.yml

- name: Include tasks 'enable_services.yml'
  include_tasks: enable_services.yml
  when: enabled_services is defined

- name: Include tasks 'disable_services.yml'
  include_tasks: disable_services.yml
  when: disabled_services is defined
