---
- include_tasks: validate_ubuntu_lts_version.yml

- name: Launch 'apt update'
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Launch 'apt upgrade'
  ansible.builtin.apt:
    upgrade: yes
  become: yes

- name: Register this host on Ubuntu Pro (pro attach <token>)
  ansible.builtin.command: "pro attach {{ ubuntu_pro_token }}"
  become: yes
  register: reg_pro_attach

- name: Print 'pro attach' command output
  ansible.builtin.debug:
    var: reg_pro_attach
