---
- name: Launch 'apt update'
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Launch 'apt upgrade'
  ansible.builtin.apt:
    upgrade: yes
  become: yes
  
- name: Register this host on Ubuntu Pro (pro attach <token>)
  command: pro attach {{ ubuntu_pro_token }}
  become: yes
  register: reg_pro_attach

- debug:
    var: reg_pro_attach
