---
- name: Register this host on Ubuntu Pro (pro attach <token>)
  ansible.builtin.command: "pro attach {{ ubuntu_pro_token }}"
  become: true
  register: _reg_pro_attach
  changed_when: _reg_pro_attach.rc == 0
  failed_when: (_reg_pro_attach.rc != 0) and ('This machine is already attached to' not in _reg_pro_attach.stderr_lines[0])

- name: Print 'pro attach' command output
  ansible.builtin.debug:
    var: _reg_pro_attach
  when: ubuntu_pro_debug
