---
- name: Check if command 'pro' exists
  ansible.builtin.shell: "command pro"
  register: _reg_command_pro
  ignore_errors: true

- name: Set variable 'pro_command_exists'
  ansible.builtin.set_fact:
    _pro_command_exists: "{{ (_reg_command_pro.rc == 127) | ternary(false, true) }}"

- name: Unregister this host on Ubuntu Pro (pro detach)
  ansible.builtin.command: "pro detach --assume-yes"
  become: true
  register: _reg_pro_detach
  changed_when: _reg_pro_detach.rc == 0
  failed_when: (_reg_pro_detach.rc != 0) and ('This machine is not attached to an Ubuntu Pro subscription.' not in _reg_pro_detach.stderr_lines[0])
  when: _pro_command_exists

- name: Print 'pro detach' command output
  ansible.builtin.debug:
    var: _reg_pro_detach
  when: (ubuntu_pro_debug and _pro_command_exists)
